
package main;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author baibu
 */
public class CheckoutUI extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutUI
     */
    public CheckoutUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        paymentIDtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paymenyDatetxt = new javax.swing.JTextField();
        TotalTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CashTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ChangeTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        paymentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBackground(new java.awt.Color(238, 235, 234));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel2.setText("Transaction ID:");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        paymentIDtxt.setEditable(false);
        paymentIDtxt.setBackground(new java.awt.Color(220, 219, 219));
        paymentIDtxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        panel.add(paymentIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 250, 40));

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel3.setText("Payment Date:");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        paymenyDatetxt.setEditable(false);
        paymenyDatetxt.setBackground(new java.awt.Color(220, 219, 219));
        paymenyDatetxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        panel.add(paymenyDatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 250, 40));

        TotalTxt.setEditable(false);
        TotalTxt.setBackground(new java.awt.Color(220, 219, 219));
        TotalTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        panel.add(TotalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 250, 40));

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel6.setText("Total (฿):");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        CashTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        panel.add(CashTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 250, 40));

        jLabel7.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel7.setText("Cash (฿):");
        panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        ChangeTxt.setEditable(false);
        ChangeTxt.setBackground(new java.awt.Color(220, 219, 219));
        ChangeTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        panel.add(ChangeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 250, 40));

        jLabel8.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel8.setText("Change (฿):");
        panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        orderTable.setFont(new java.awt.Font("BD Megatoya Extended Thin Itali", 0, 14)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Price", "Quantity", "Total Price"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 490, 620));

        paymentBtn.setBackground(new java.awt.Color(36, 126, 84));
        paymentBtn.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        paymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        paymentBtn.setText("Payment");
        panel.add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 250, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CheckoutUI().setVisible(true);
//            }
//        });
//    }

    public JTextField getCashTxt() {
        return CashTxt;
    }

    public void setCashTxt(JTextField CashTxt) {
        this.CashTxt = CashTxt;
    }

    public JTextField getChangeTxt() {
        return ChangeTxt;
    }

    public void setChangeTxt(JTextField ChangeTxt) {
        this.ChangeTxt = ChangeTxt;
    }



    public JTextField getTotalTxt() {
        return TotalTxt;
    }

    public void setTotalTxt(JTextField TotalTxt) {
        this.TotalTxt = TotalTxt;
    }

    public JTable getOrderTable() {
        return orderTable;
    }





    public JPanel getPanel() {
        return panel;
    }

    public void setPanel(JPanel panel) {
        this.panel = panel;
    }

    public JButton getPaymentBtn() {
        return paymentBtn;
    }

    public void setPaymentBtn(JButton paymentBtn) {
        this.paymentBtn = paymentBtn;
    }

    public JTextField getPaymentIDtxt() {
        return paymentIDtxt;
    }

    public void setPaymentIDtxt(JTextField paymentIDtxt) {
        this.paymentIDtxt = paymentIDtxt;
    }

    public JTextField getPaymenyDatetxt() {
        return paymenyDatetxt;
    }

    public void setPaymenyDatetxt(JTextField paymenyDatetxt) {
        this.paymenyDatetxt = paymenyDatetxt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CashTxt;
    private javax.swing.JTextField ChangeTxt;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JPanel panel;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JTextField paymentIDtxt;
    private javax.swing.JTextField paymenyDatetxt;
    // End of variables declaration//GEN-END:variables
}
