
package main;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author baibu
 */
public class CheckoutUI extends javax.swing.JFrame {

    /**
     * Creates new form CheckoutUI
     */
    public CheckoutUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        paymentIDtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        paymenyDatetxt = new javax.swing.JTextField();
        TotalTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CashTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ChangeTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        paymentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel.setBackground(new java.awt.Color(238, 235, 234));

        jLabel2.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel2.setText("Transaction ID:");

        paymentIDtxt.setEditable(false);
        paymentIDtxt.setBackground(new java.awt.Color(220, 219, 219));
        paymentIDtxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel3.setText("Payment Date:");

        paymenyDatetxt.setEditable(false);
        paymenyDatetxt.setBackground(new java.awt.Color(220, 219, 219));
        paymenyDatetxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        TotalTxt.setEditable(false);
        TotalTxt.setBackground(new java.awt.Color(220, 219, 219));
        TotalTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel6.setText("Total (฿):");

        CashTxt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel7.setText("Cash (฿):");

        ChangeTxt.setEditable(false);
        ChangeTxt.setBackground(new java.awt.Color(220, 219, 219));
        ChangeTxt.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        jLabel8.setText("Change (฿):");

        orderTable.setFont(new java.awt.Font("BD Megatoya Extended Thin Itali", 0, 14)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Price", "Quantity", "Total Price"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        paymentBtn.setBackground(new java.awt.Color(36, 126, 84));
        paymentBtn.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        paymentBtn.setForeground(new java.awt.Color(255, 255, 255));
        paymentBtn.setText("Payment");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(paymentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(paymenyDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CashTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(ChangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(180, 180, 180)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addComponent(paymentIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(paymenyDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(CashTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(7, 7, 7)
                        .addComponent(ChangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(paymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CheckoutUI().setVisible(true);
//            }
//        });
//    }

    public JTextField getCashTxt() {
        return CashTxt;
    }

    public void setCashTxt(JTextField CashTxt) {
        this.CashTxt = CashTxt;
    }

    public JTextField getChangeTxt() {
        return ChangeTxt;
    }

    public void setChangeTxt(JTextField ChangeTxt) {
        this.ChangeTxt = ChangeTxt;
    }



    public JTextField getTotalTxt() {
        return TotalTxt;
    }

    public void setTotalTxt(JTextField TotalTxt) {
        this.TotalTxt = TotalTxt;
    }

    public JTable getOrderTable() {
        return orderTable;
    }





    public JPanel getPanel() {
        return panel;
    }

    public void setPanel(JPanel panel) {
        this.panel = panel;
    }

    public JButton getPaymentBtn() {
        return paymentBtn;
    }

    public void setPaymentBtn(JButton paymentBtn) {
        this.paymentBtn = paymentBtn;
    }

    public JTextField getPaymentIDtxt() {
        return paymentIDtxt;
    }

    public void setPaymentIDtxt(JTextField paymentIDtxt) {
        this.paymentIDtxt = paymentIDtxt;
    }

    public JTextField getPaymenyDatetxt() {
        return paymenyDatetxt;
    }

    public void setPaymenyDatetxt(JTextField paymenyDatetxt) {
        this.paymenyDatetxt = paymenyDatetxt;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CashTxt;
    private javax.swing.JTextField ChangeTxt;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JPanel panel;
    private javax.swing.JButton paymentBtn;
    private javax.swing.JTextField paymentIDtxt;
    private javax.swing.JTextField paymenyDatetxt;
    // End of variables declaration//GEN-END:variables
}
