
package main;

import javax.swing.*;

/**
 *
 * @author baibu
 */
public class CreateOrderUI extends javax.swing.JFrame {

    /**
     * Creates new form CreateOrderUI
     */
    public CreateOrderUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        clearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(238, 235, 234));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setText("Select Menu:");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 160, 40));

        orderTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Price", "Quantity", "Total Price"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        panel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 410, 470));

        total.setFont(new java.awt.Font("sansserif", 1, 22)); // NOI18N
        total.setText("Total (฿): 0.0");
        panel.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 210, 40));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Quantity:");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 80, 30));
        panel.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 100, -1));

        removeBtn.setText("Remove from List");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        panel.add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 650, 180, 30));

        checkoutBtn.setBackground(new java.awt.Color(36, 126, 84));
        checkoutBtn.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Check Out");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });
        panel.add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 170, 90));

        addBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        addBtn.setText("Add to Order");
        panel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 170, 70));

        searchTxt.setText("Search..");
        panel.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 230, -1));

        backBtn.setBackground(new java.awt.Color(163, 46, 46));
        backBtn.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        panel.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        menuTable.setFont(new java.awt.Font("BD Megatoya Extended Thin Itali", 0, 14)); // NOI18N
        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Image", "Name", "Description", "Price"
            }
        ));
        jScrollPane1.setViewportView(menuTable);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 370, 480));

        clearBtn.setText("Clear All Menu.");
        panel.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 650, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateOrderUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable menuTable;
    private javax.swing.JTable orderTable;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables

    public JButton getAddBtn() {
        return addBtn;
    }

    public void setAddBtn(JButton addBtn) {
        this.addBtn = addBtn;
    }

    public JButton getBackBtn() {
        return backBtn;
    }

    public void setBackBtn(JButton backBtn) {
        this.backBtn = backBtn;
    }

    public JButton getCheckoutBtn() {
        return checkoutBtn;
    }

    public void setCheckoutBtn(JButton checkoutBtn) {
        this.checkoutBtn = checkoutBtn;
    }

    public JButton getClearBtn() {
        return clearBtn;
    }

    public JPanel getPanel() {
        return panel;
    }

    public void setPanel(JPanel panel) {
        this.panel = panel;
    }

    public JButton getRemoveBtn() {
        return removeBtn;
    }

    public JTextField getQuantity(){
        return this.quantity;
    }
    public void setQuantity(JTextField quantity){
        this.quantity = quantity;
    }

    public JTable getMenuTable() {
        return menuTable;
    }

    public JTable getOrderTable() {
        return orderTable;
    }

    public JTextField getSearchTxt() {
        return searchTxt;
    }

    public JLabel getTotal() {
        return total;
    }

}
