/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author baibu
 */
public class HomeUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI
     */
    public HomeUI() {
        initComponents();
    }
    public JPanel getPanel() {
        return this.panel;
    }
    
    public JButton getBtnCreateOrder() {
        return this.btnCreateOrder;
    }
    public JButton getBtnManageMenu() {
        return this.btnManageMenu;
    }
    public JButton getBtnSaleReport() {
        return this.btnViewSaleReport;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    
    public JLabel getCurrentusername() {
        return currentusername;
    }

    public JLabel getjDate() {
        return jDate;
    }

    public JLabel getjPMAM() {
        return jPMAM;
    }

    public JLabel getjTime() {
        return jTime;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        currentusername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Bannyang = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jPMAM = new javax.swing.JLabel();
        jTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnViewSaleReport = new javax.swing.JButton();
        btnManageMenu = new javax.swing.JButton();
        btnCreateOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(201, 193, 188));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        currentusername.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        currentusername.setForeground(new java.awt.Color(243, 242, 242));
        currentusername.setText("welcome, username");
        panel.add(currentusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 540, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BAANYANGCHA.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 80));

        Bannyang.setBackground(new java.awt.Color(234, 235, 238));
        Bannyang.setFont(new java.awt.Font("Angsana New", 1, 60)); // NOI18N
        Bannyang.setForeground(new java.awt.Color(248, 247, 247));
        Bannyang.setText("BannYang Cha.");
        panel.add(Bannyang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 370, -1));

        jDate.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDate.setForeground(new java.awt.Color(243, 242, 242));
        jDate.setText("Saturday, 21/10/2023");
        panel.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 220, -1));

        jPMAM.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPMAM.setForeground(new java.awt.Color(243, 242, 242));
        jPMAM.setText("PM");
        panel.add(jPMAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, 40, -1));

        jTime.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTime.setForeground(new java.awt.Color(243, 242, 242));
        jTime.setText("00:00:00");
        panel.add(jTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 90, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setText("View Sale's");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 200, 80));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Report");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 120, 80));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setText("Create Order");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 230, 80));

        btnViewSaleReport.setBackground(new java.awt.Color(255, 255, 255));
        btnViewSaleReport.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnViewSaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSaleReportActionPerformed(evt);
            }
        });
        panel.add(btnViewSaleReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 300, 180));

        btnManageMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnManageMenu.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        btnManageMenu.setText("Manage Menu");
        btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMenuActionPerformed(evt);
            }
        });
        panel.add(btnManageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 300, 180));

        btnCreateOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateOrder.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        panel.add(btnCreateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 300, 180));

        jPanel2.setBackground(new java.awt.Color(236, 238, 241, 30));

        btnLogout.setBackground(new java.awt.Color(17, 16, 16));
        btnLogout.setFont(new java.awt.Font("BD Megatoya Outline Black Itali", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(245, 240, 240));
        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("© 2023 BaanYang Cha Inc.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnLogout)
                .addGap(452, 452, 452)
                .addComponent(jLabel3)
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(677, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(btnLogout))
                .addGap(15, 15, 15))
        );

        panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signupcafe.jpg"))); // NOI18N
        bg.setText("jLabel2");
        panel.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewSaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSaleReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewSaleReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageMenuActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bannyang;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageMenu;
    private javax.swing.JButton btnViewSaleReport;
    private javax.swing.JLabel currentusername;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jPMAM;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jTime;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables


}
