/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author baibu
 */
public class HomeUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeUI
     */
    public HomeUI() {
        initComponents();
    }
    public JPanel getPanel() {
        return this.panel;
    }
    
    public JButton getBtnCreateOrder() {
        return this.btnCreateOrder;
    }
    public JButton getBtnManageMenu() {
        return this.btnManageMenu;
    }
    public JButton getBtnSaleReport() {
        return this.btnViewSaleReport;
    }

    
    public JLabel getCurrentusername() {
        return currentusername;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        copyright_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnManageMenu = new javax.swing.JButton();
        btnCreateOrder = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnViewSaleReport = new javax.swing.JButton();
        Bannyang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        currentusername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(201, 193, 188));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        copyright_panel.setBackground(new java.awt.Color(40, 38, 38));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("© 2023 BaanYang Cha Inc.");

        javax.swing.GroupLayout copyright_panelLayout = new javax.swing.GroupLayout(copyright_panel);
        copyright_panel.setLayout(copyright_panelLayout);
        copyright_panelLayout.setHorizontalGroup(
            copyright_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, copyright_panelLayout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(440, 440, 440))
        );
        copyright_panelLayout.setVerticalGroup(
            copyright_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(copyright_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panel.add(copyright_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 1090, 40));

        btnManageMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnManageMenu.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnManageMenu.setText("Manage Menu");
        btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMenuActionPerformed(evt);
            }
        });
        panel.add(btnManageMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 300, 180));

        btnCreateOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateOrder.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnCreateOrder.setText("Create Order");
        panel.add(btnCreateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 300, 180));

        btnLogout.setBackground(new java.awt.Color(169, 3, 3));
        btnLogout.setFont(new java.awt.Font("BD Megatoya Outline Black Itali", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(245, 240, 240));
        btnLogout.setText("logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        panel.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 100, 40));

        btnViewSaleReport.setBackground(new java.awt.Color(255, 255, 255));
        btnViewSaleReport.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        btnViewSaleReport.setText("View Sale's Report");
        btnViewSaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSaleReportActionPerformed(evt);
            }
        });
        panel.add(btnViewSaleReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 300, 180));

        Bannyang.setFont(new java.awt.Font("Angsana New", 1, 60)); // NOI18N
        Bannyang.setForeground(new java.awt.Color(219, 218, 218));
        Bannyang.setText("BannYang Cha.");
        panel.add(Bannyang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 370, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/homecafe.jpg"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(530, 800));
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 820));

        jLabel1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel1.setText("Saturday, 21-10-2023");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, 160, -1));

        jLabel4.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabel4.setText("00:00:00 PM");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 110, -1));

        currentusername.setFont(new java.awt.Font("Angsana New", 0, 28)); // NOI18N
        currentusername.setText("welcome, username");
        panel.add(currentusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewSaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSaleReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewSaleReportActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bannyang;
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageMenu;
    private javax.swing.JButton btnViewSaleReport;
    private javax.swing.JPanel copyright_panel;
    private javax.swing.JLabel currentusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables


}
