/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author baibu
 */
public class SignupUI extends javax.swing.JFrame {

    /**
     * Creates new form SignupUI
     */
    public SignupUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Email_Message = new javax.swing.JLabel();
        jLabel_Username_Message = new javax.swing.JLabel();
        jLabel_Password_Message = new javax.swing.JLabel();
        jLabel_ConPassword_Message = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        password2 = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(229, 225, 225, 240));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel2.setText("Create a new account");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 37, 379, 43));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Sign up now and unlock exclusive access!");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 98, 350, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 166, 55, -1));

        email.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 194, 351, 37));

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel5.setText("Username");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 265, 85, -1));

        username.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 293, 350, 37));

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 364, 87, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel7.setText("Confirm Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 465, 137, -1));

        signupbtn.setBackground(new java.awt.Color(16, 110, 77));
        signupbtn.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        signupbtn.setForeground(new java.awt.Color(255, 255, 255));
        signupbtn.setText("Sign Up");
        jPanel2.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 604, 351, 54));

        jLabel8.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel8.setText("                  Already a member?");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 753, -1, -1));

        jLabel_Email_Message.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Email_Message.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel_Email_Message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel_Email_Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 237, 308, 22));

        jLabel_Username_Message.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Username_Message.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel_Username_Message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel_Username_Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 336, 303, 22));

        jLabel_Password_Message.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Password_Message.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel_Password_Message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel_Password_Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 435, 302, 24));

        jLabel_ConPassword_Message.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ConPassword_Message.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        jLabel_ConPassword_Message.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel_ConPassword_Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 536, 301, 25));

        password1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        password1.setForeground(new java.awt.Color(51, 51, 51));
        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });
        jPanel2.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 350, 40));

        password2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        password2.setForeground(new java.awt.Color(51, 51, 51));
        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });
        jPanel2.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 391, 350, 38));

        loginbtn.setBackground(new java.awt.Color(255, 255, 255));
        loginbtn.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(70, 162, 255));
        loginbtn.setText("Sign In");
        jPanel2.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 748, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 520, 820));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/signupcafe.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 1090, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password1ActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupUI().setVisible(true);
            }
        });
    }
    public JPasswordField getPassword1() {
        return password1;
    }

    public JPasswordField getPassword2() {
        return password2;
    }

    public JButton getSignupbtn() {
        return signupbtn;
    }

    public JTextField getUsername() {
        return username;
    }
    
    public JTextField getEmail() {
        return email;
    }

    public JButton getLoginbtn() {
        return loginbtn;
    }
    


    public JLabel getjLabel_ConPassword_Message() {
        return jLabel_ConPassword_Message;
    }

    public JLabel getjLabel_Email_Message() {
        return jLabel_Email_Message;
    }

    public JLabel getjLabel_Password_Message() {
        return jLabel_Password_Message;
    }

    public JLabel getjLabel_Username_Message() {
        return jLabel_Username_Message;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_ConPassword_Message;
    private javax.swing.JLabel jLabel_Email_Message;
    private javax.swing.JLabel jLabel_Password_Message;
    private javax.swing.JLabel jLabel_Username_Message;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField password1;
    private javax.swing.JPasswordField password2;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
